### ISSUE TITLE
ROM is a massive kang

### ISSUE THREAD

**Issue by mcl21014** [AOSParadox/AOSParadox#5]
Waste of space on the internet. I would've rather had it been taken up by petabytes of porno than this garbage. At least the porn is more original than "your" code. By the way, fuck you guys.

┌∩┐(◣_◢)┌∩┐

**Comment by Thecrazyskull** [comment]
Alright, when do you wanna  fuck? :):):)

**Comment by miguepereira77** [comment]
?????
I´m sorry...What?


2015-12-05 11:10 GMT+01:00 Anas Karbila <notifications@github.com>:
