### ISSUE TITLE
┌∩┐(◣_◢)┌∩┐

### ISSUE THREAD

**Issue by cannondalev2000** [AOSParadox/AOSParadox#6]
┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐┌∩┐(◣_◢)┌∩┐

**Comment by h2o64** [comment]
You spelled it wrong
